# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"open_geotiff": "00_image.ipynb",
         "calc_normalized_spectral_index": "00_image.ipynb",
         "calc_avi": "00_image.ipynb",
         "calc_savi": "00_image.ipynb",
         "calc_gci": "00_image.ipynb",
         "mask_plot_from_image": "00_image.ipynb",
         "calc_image_metrics": "00_image.ipynb",
         "get_image_metric_cols": "00_image.ipynb",
         "plot_point_cloud": "01_las.ipynb",
         "plot_2d_views": "01_las.ipynb",
         "las_to_df": "01_las.ipynb",
         "mask_plot_from_lidar": "01_las.ipynb",
         "calc_lidar_metrics": "01_las.ipynb",
         "get_las_metric_cols": "01_las.ipynb",
         "voxel_grid_from_las": "01_las.ipynb",
         "get_lidar_procs": "02_tabular.ipynb",
         "get_image_procs": "02_tabular.ipynb"}

modules = ["image.py",
           "las.py",
           "tabular_models.py"]

doc_url = "https://jaeeolma.github.io/enveco/"

git_url = "https://github.com/jaeeolma/enveco/tree/master/"

def custom_doc_links(name): return None
