# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_tabular.ipynb (unless otherwise specified).

__all__ = ['get_lidar_procs', 'get_image_procs']

# Cell
from fastai.tabular.all import *
from fastai.data.all import *
from .las import *
from .image import *

# Cell

def get_lidar_procs(row, path, mask_plot=True):
    "Function for LiDAR opening and processing steps"
    las_data = las_to_df(f'{path}/{row.sampleplotid}.las')
    if mask_plot == True: las_data = mask_plot_from_lidar(las_data, row.x, row.y)
    metrics = calc_lidar_metrics(las_data)
    return metrics

# Cell

def get_image_procs(row, path, mask_plot=True):
    "Function for tif opening and processing steps"
    image_data = open_geotiff(f'{path}/{row.sampleplotid}.tif')
    if mask_plot == True: image_data = mask_plot_from_image(image_data, radius=31)
    metrics = calc_image_metrics(image_data)
    return metrics